### PR TITLE
Create a test suite for nimbusapp

### PR DESCRIPTION
**Pull request by jasoncorlett**
* Add test cases for basic use, caching and --set
* Fix bug with cache directory discovered in testing
* Created some assert functions for common docker tests

### CODE REVIEW

**Review by jhrabi — COMMENTED** [review]
I'm assuming bats are the test cases? What's the naming convention here?

**Comment by jasoncorlett** [comment]
> I'm assuming bats are the test cases? What's the naming convention here?

Yes, .bats files are tests (each one can have a series of \@test functions). The .bash files are helper scripts that contain some reusable functions/variables. I'll update the README to include some more details on the tests.

**Comment by jhrabi** [comment]
I was more asking why the 00_basic.bats naming convention. What's the numbers in front of the test for? Execution order?

**Comment by jasoncorlett** [comment]
> I was more asking why the 00_basic.bats naming convention. What's the numbers in front of the test for? Execution order?

Yes, since I usually run the tests with `bats tests/*.bats` , the numbers control the order tests are executed.

**Comment by jhrabi** [comment]
> > I was more asking why the 00_basic.bats naming convention. What's the numbers in front of the test for? Execution order?
> 
> Yes, since I usually run the tests with `bats tests/*.bats` , the numbers control the order tests are executed.

Okay. I was going to ask if execution order matters, but if we're gonna re-write this is a new language this probably a small point.

**Review by jhrabi — APPROVED** [review]

**Comment by jasoncorlett** [comment]
Order doesn't really matter, other than wanting to run the more basic tests before the more involved ones. Depending on the other language and the command format, these tests could still be relevant.

**Pull request merged**
