### PR TITLE
Major refactor of nimbusapp

### PR DESCRIPTION
**Pull request by jhrabi**
- What I did

Cleaned up how repository, image and tag are determined
Cleaned up help files to reduced large number of tabs
Added functionality for logs, ps, rm for compose and render and inspect for docker-app
Combined actions into one part of case statement
Removed action check, as docker-compose will catch this
Added gitignore file
Set env file to exist in ${HOME}/.nimbusapp/env
Removed references to product, as everything should be considered from an image perspective
Combined creation of commands based upon different conditions.

### CODE REVIEW

**Comment by panama69** [comment]
Maybe we should rename the file 'env' to say "apps", "availableapps" or something like that.

**Comment by jhrabi** [comment]
How about apps.config?

**Comment by panama69** [comment]
That sounds good.

**Comment by jhrabi** [comment]
Are you okay with the rest? Waiting on approval from you.

**Comment by panama69** [comment]
yes, looks like you added and considered some things that I hadn't thought of.

**Comment by jhrabi** [comment]
Can you please add your approved review then, and I'll merge. Thanks.

**Review by panama69 — APPROVED** [review]

**Pull request merged**
