### PR TITLE
1.1.0

### PR DESCRIPTION
**Pull request by panama69**
Seems this branch was never merged though I believe this is what you released with the latest NimbusServer image

### CODE REVIEW

**Comment by jhrabi** [comment]
This is still a development branch. Version on nimbusserver was marked 1.0.0

**Comment by jhrabi** [comment]
That said, I can mark this for a 1.1.0 release to add these features in.

**Comment by panama69** [comment]
so not sure where we go.  should this be merged or continue on as a dev branch?

**Comment by jhrabi** [comment]
This should be continued as a dev branch until we're ready to release the next iteration.

**Comment by panama69** [comment]
so i should cancel the pull request?  right?

**Comment by jhrabi** [comment]
Yes, unless you just want to release 1.1.0 with the pull and restart features. I'm good either way.

**Comment by panama69** [comment]
we will close for now and wait till later

**Pull request closed without merging**
